name:                gwcli
version:             0.1.0.0
github:              "diskshima/gwcli-hs"
license:             BSD3
author:              "Daisuke Shimamoto"
maintainer:          "diskshima@gmail.com"
copyright:           "2018 Daisuke Shimamoto"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/diskshima/gwcli-hs#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- aeson-casing
- bytestring
- git
- lens
- network-uri
- string-conversions
- utf8-string
- wreq
- yaml

library:
  source-dirs: src

executables:
  gwcli:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gwcli

tests:
  gwcli-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gwcli-hs
