name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache Stack files
      uses: actions/cache@v2
      with:
        path: |
          ~/.stack/
          .stack-work/
        key: ${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}
    - name: Setup Stack
      uses: mstksg/setup-stack@v2
    - name: Run build
      run: stack build
    - name: Output Stack local bin directory
      id: output_stack
      run: echo "::set-output name=local_bin::$(stack path --local-bin)"
    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: gwcli
        path: ${{ steps.output_stack.outputs.local_bin }}/gwcli
