---
name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact (macOS)
        uses: actions/download-artifact@v4
        with:
          name: gwcli_macos
          path: macos
      - name: Download build artifact (Linux)
        uses: actions/download-artifact@v4
        with:
          name: gwcli_linux
          path: linux
      - name: Copy and rename artifacts
        run: |
          cp macos/gwcli gwcli_macos
          cp linux/gwcli gwcli_linux
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: |
            gwcli_macos
            gwcli_linux
